global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'
  group_interval: 5m
  repeat_interval: 4h
  group_wait: 0s

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#grafana-notification'
        send_resolved: true
        text: |
          🚨 Alert: {{ .CommonLabels.alertname }}
          Instance: {{ or .CommonLabels.instance "unknown" }}
          Status: {{ .Status }}
